name: Pull Request Locally Test Merge Into Master

on:
  pull_request:
    branches:
      - master

jobs:
  prBuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Print Environment Variables
        run: printenv
      - name: Build Docker Image
        id: build_docker_image
        run: make docker-build

