name: Pull Request Locally Test Merge Into Master

on:
  pull_request:
    branches:
      - master

jobs:
  pullRequestBuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Print Environment Variables
        run: printenv
      - name: Check out to branch
        run: git checkout ${GITHUB_HEAD_REF:-${GITHUB_REF##*/}}
      - name: Merge master into branch
        run: git merge origin/master
      - name: Build Docker Image
        id: build_docker_image
        run: make docker-build

