name: CI Test Build On Push Event For A Commit

on:
  push:
    branches-ignore:
      - master

jobs:
  pushBuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Print Environment Variables
        run: printenv
      - name: Check out to branch
        run: git checkout origin/${GITHUB_HEAD_REF:-${GITHUB_REF##*/}}
      - name: Build Docker Image
        id: build_docker_image
        run: |
          make \
            GITHUB_HEAD_REF=${GITHUB_HEAD_REF:-${GITHUB_REF##*/}} \
            GITHUB_EVENT_NAME=${GITHUB_EVENT_NAME} \
            docker-build